In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
df=pd.read_csv(r"D:\Big Data Analytics- Sem 3\Capstone Project\Toronto\listing.csv\listings.csv")

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21115 entries, 0 to 21114
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            21115 non-null  int64
 1   listing_url                                   21115 non-null  object
 2   scrape_id                                     21115 non-null  int64
 3   last_scraped                                  21115 non-null  object
 4   source                                        21115 non-null  object
 5   name                                          21115 non-null  object
 6   description                                   20560 non-null  object
 7   neighborhood_overview                         11111 non-null  object
 8   picture_url                                   21115 non-null  object
 9   host_id                                       21115 non-null  int64
 10  host_url                                      21115 non-null  object
 11  host_name                                     21113 non-null  object
 12  host_since                                    21113 non-null  object
 13  host_location                                 15647 non-null  object
 14  host_about                                    9846 non-null   object
 15  host_response_time                            15043 non-null  object
 16  host_response_rate                            15043 non-null  object
 17  host_acceptance_rate                          15765 non-null  object
 18  host_is_superhost                             20741 non-null  object
 19  host_thumbnail_url                            21113 non-null  object
 20  host_picture_url                              21113 non-null  object
 21  host_neighbourhood                            8464 non-null   object
 22  host_listings_count                           21113 non-null  float64
 23  host_total_listings_count                     21113 non-null  float64
 24  host_verifications                            21113 non-null  object
 25  host_has_profile_pic                          21113 non-null  object
 26  host_identity_verified                        21113 non-null  object
 27  neighbourhood                                 11112 non-null  object
 28  neighbourhood_cleansed                        21115 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      21115 non-null  float64
 31  longitude                                     21115 non-null  float64
 32  property_type                                 21115 non-null  object
 33  room_type                                     21115 non-null  object
 34  accommodates                                  21115 non-null  int64
 35  bathrooms                                     15901 non-null  float64
 36  bathrooms_text                                21107 non-null  object
 37  bedrooms                                      19627 non-null  float64
 38  beds                                          15888 non-null  float64
 39  amenities                                     21115 non-null  object
 40  price                                         15903 non-null  object
 41  minimum_nights                                21115 non-null  int64
 42  maximum_nights                                21115 non-null  int64
 43  minimum_minimum_nights                        21115 non-null  int64
 44  maximum_minimum_nights                        21115 non-null  int64
 45  minimum_maximum_nights                        21115 non-null  int64
 46  maximum_maximum_nights                        21115 non-null  int64
 47  minimum_nights_avg_ntm                        21115 non-null  float64
 48  maximum_nights_avg_ntm                        21115 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              20090 non-null  object
 51  availability_30                               21115 non-null  int64
 52  availability_60                               21115 non-null  int64
 53  availability_90                               21115 non-null  int64
 54  availability_365                              21115 non-null  int64
 55  calendar_last_scraped                         21115 non-null  object
 56  number_of_reviews                             21115 non-null  int64
 57  number_of_reviews_ltm                         21115 non-null  int64
 58  number_of_reviews_l30d                        21115 non-null  int64
 59  first_review                                  15677 non-null  object
 60  last_review                                   15677 non-null  object
 61  review_scores_rating                          15677 non-null  float64
 62  review_scores_accuracy                        15643 non-null  float64
 63  review_scores_cleanliness                     15642 non-null  float64
 64  review_scores_checkin                         15643 non-null  float64
 65  review_scores_communication                   15643 non-null  float64
 66  review_scores_location                        15642 non-null  float64
 67  review_scores_value                           15643 non-null  float64
 68  license                                       10103 non-null  object
 69  instant_bookable                              21115 non-null  object
 70  calculated_host_listings_count                21115 non-null  int64
 71  calculated_host_listings_count_entire_homes   21115 non-null  int64
 72  calculated_host_listings_count_private_rooms  21115 non-null  int64
 73  calculated_host_listings_count_shared_rooms   21115 non-null  int64
 74  reviews_per_month                             15677 non-null  float64
dtypes: float64(19), int64(21), object(35)
memory usage: 12.1+ MB

In [52]:
df = df.drop(['listing_url', 'scrape_id', 'last_scraped', 'name', 'picture_url', 'host_url', 'host_name', 'host_thumbnail_url', 'host_picture_url', 'neighbourhood_group_cleansed', 'calendar_updated', 'latitude', 'longitude'], axis=1)

In [53]:
'''
df1=df.drop(['id', 'host_id', 'description', 'neighborhood_overview', 'host_since','host_about', 'latitude', 'longitude', 'host_location', 'amenities', 'first_review', 'last_review'], axis=1)
index = df1.columns
for i in index:
    print(df1[i].value_counts())
    print("-------------------------------")
    '''

'\ndf1=df.drop([\'id\', \'host_id\', \'description\', \'neighborhood_overview\', \'host_since\',\'host_about\', \'latitude\', \'longitude\', \'host_location\', \'amenities\', \'first_review\', \'last_review\'], axis=1)\nindex = df1.columns\nfor i in index:\n    print(df1[i].value_counts())\n    print("-------------------------------")\n    '

In [54]:
df=df.drop(['minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights','maximum_maximum_nights', 'availability_30', 'availability_60', 'availability_90'],axis=1)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21115 entries, 0 to 21114
Data columns (total 55 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            21115 non-null  int64
 1   source                                        21115 non-null  object
 2   description                                   20560 non-null  object
 3   neighborhood_overview                         11111 non-null  object
 4   host_id                                       21115 non-null  int64
 5   host_since                                    21113 non-null  object
 6   host_location                                 15647 non-null  object
 7   host_about                                    9846 non-null   object
 8   host_response_time                            15043 non-null  object
 9   host_response_rate                            15043 non-null  object
 10  host_acceptance_rate                          15765 non-null  object
 11  host_is_superhost                             20741 non-null  object
 12  host_neighbourhood                            8464 non-null   object
 13  host_listings_count                           21113 non-null  float64
 14  host_total_listings_count                     21113 non-null  float64
 15  host_verifications                            21113 non-null  object
 16  host_has_profile_pic                          21113 non-null  object
 17  host_identity_verified                        21113 non-null  object
 18  neighbourhood                                 11112 non-null  object
 19  neighbourhood_cleansed                        21115 non-null  object
 20  property_type                                 21115 non-null  object
 21  room_type                                     21115 non-null  object
 22  accommodates                                  21115 non-null  int64
 23  bathrooms                                     15901 non-null  float64
 24  bathrooms_text                                21107 non-null  object
 25  bedrooms                                      19627 non-null  float64
 26  beds                                          15888 non-null  float64
 27  amenities                                     21115 non-null  object
 28  price                                         15903 non-null  object
 29  minimum_nights                                21115 non-null  int64
 30  maximum_nights                                21115 non-null  int64
 31  minimum_nights_avg_ntm                        21115 non-null  float64
 32  maximum_nights_avg_ntm                        21115 non-null  float64
 33  has_availability                              20090 non-null  object
 34  availability_365                              21115 non-null  int64
 35  calendar_last_scraped                         21115 non-null  object
 36  number_of_reviews                             21115 non-null  int64
 37  number_of_reviews_ltm                         21115 non-null  int64
 38  number_of_reviews_l30d                        21115 non-null  int64
 39  first_review                                  15677 non-null  object
 40  last_review                                   15677 non-null  object
 41  review_scores_rating                          15677 non-null  float64
 42  review_scores_accuracy                        15643 non-null  float64
 43  review_scores_cleanliness                     15642 non-null  float64
 44  review_scores_checkin                         15643 non-null  float64
 45  review_scores_communication                   15643 non-null  float64
 46  review_scores_location                        15642 non-null  float64
 47  review_scores_value                           15643 non-null  float64
 48  license                                       10103 non-null  object
 49  instant_bookable                              21115 non-null  object
 50  calculated_host_listings_count                21115 non-null  int64
 51  calculated_host_listings_count_entire_homes   21115 non-null  int64
 52  calculated_host_listings_count_private_rooms  21115 non-null  int64
 53  calculated_host_listings_count_shared_rooms   21115 non-null  int64
 54  reviews_per_month                             15677 non-null  float64
dtypes: float64(15), int64(13), object(27)
memory usage: 8.9+ MB

In [56]:
selected_columns = ['calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'host_listings_count', 'host_total_listings_count']
df_selected = df[selected_columns]
df_selected.head(5)

,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,host_listings_count,host_total_listings_count
0,1,1,0,0,1.0,1.0
1,1,1,0,0,1.0,3.0
2,2,1,1,0,2.0,3.0
3,1,1,0,0,1.0,3.0
4,1,1,0,0,5.0,5.0

calculated_host_listings_count: This column represents the total number of listings that a host has on Airbnb, as calculated by Airbnb.
calculated_host_listings_count_entire_homes: This column represents the number of entire home listings that a host has on Airbnb, as calculated by Airbnb.
calculated_host_listings_count_private_rooms: This column represents the number of private room listings that a host has on Airbnb, as calculated by Airbnb.
calculated_host_listings_count_shared_rooms: This column represents the number of shared room listings that a host has on Airbnb, as calculated by Airbnb.
host_listings_count: This column represents the number of listings that a host has on Airbnb, as reported by the host themselves.
host_total_listings_count: This column represents the total number of listings that a host has on Airbnb, as reported by the host themselves.

In [57]:
df=df.drop(['calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'host_listings_count', 'host_total_listings_count'], axis=1)

In [58]:
df = df.drop(['review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value'], axis=1)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21115 entries, 0 to 21114
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              21115 non-null  int64
 1   source                          21115 non-null  object
 2   description                     20560 non-null  object
 3   neighborhood_overview           11111 non-null  object
 4   host_id                         21115 non-null  int64
 5   host_since                      21113 non-null  object
 6   host_location                   15647 non-null  object
 7   host_about                      9846 non-null   object
 8   host_response_time              15043 non-null  object
 9   host_response_rate              15043 non-null  object
 10  host_acceptance_rate            15765 non-null  object
 11  host_is_superhost               20741 non-null  object
 12  host_neighbourhood              8464 non-null   object
 13  host_verifications              21113 non-null  object
 14  host_has_profile_pic            21113 non-null  object
 15  host_identity_verified          21113 non-null  object
 16  neighbourhood                   11112 non-null  object
 17  neighbourhood_cleansed          21115 non-null  object
 18  property_type                   21115 non-null  object
 19  room_type                       21115 non-null  object
 20  accommodates                    21115 non-null  int64
 21  bathrooms                       15901 non-null  float64
 22  bathrooms_text                  21107 non-null  object
 23  bedrooms                        19627 non-null  float64
 24  beds                            15888 non-null  float64
 25  amenities                       21115 non-null  object
 26  price                           15903 non-null  object
 27  minimum_nights                  21115 non-null  int64
 28  maximum_nights                  21115 non-null  int64
 29  minimum_nights_avg_ntm          21115 non-null  float64
 30  maximum_nights_avg_ntm          21115 non-null  float64
 31  has_availability                20090 non-null  object
 32  availability_365                21115 non-null  int64
 33  calendar_last_scraped           21115 non-null  object
 34  number_of_reviews               21115 non-null  int64
 35  number_of_reviews_ltm           21115 non-null  int64
 36  number_of_reviews_l30d          21115 non-null  int64
 37  first_review                    15677 non-null  object
 38  last_review                     15677 non-null  object
 39  review_scores_rating            15677 non-null  float64
 40  license                         10103 non-null  object
 41  instant_bookable                21115 non-null  object
 42  calculated_host_listings_count  21115 non-null  int64
 43  reviews_per_month               15677 non-null  float64
dtypes: float64(7), int64(10), object(27)
memory usage: 7.1+ MB

In [60]:

# Forward fill missing values in host_since column with values from first review column
df['host_since'] = df['host_since'].fillna(df['first_review'])
# Show null values in host_since column
print(df['host_since'].isnull().sum())

1

In [61]:
# Show entire row with null value in host_since column
print(df.loc[df['host_since'].isnull()])

            id           source description neighborhood_overview   host_id  \
2799  17417181  previous scrape         NaN                   NaN  75779190

     host_since host_location host_about host_response_time  \
2799        NaN           NaN        NaN                NaN

     host_response_rate  ... number_of_reviews number_of_reviews_ltm  \
2799                NaN  ...                 0                     0

     number_of_reviews_l30d first_review last_review review_scores_rating  \
2799                      0          NaN         NaN                  NaN

     license instant_bookable calculated_host_listings_count reviews_per_month
2799     NaN                f                              1               NaN

[1 rows x 44 columns]

In [62]:
# Drop entire row with null value in host_since column
df = df.dropna(subset=['host_since'])

In [63]:
# Replace NaN values with 0
#df['host_since'] = df['host_since'].fillna('0000-00-00')

# Extract the year from the host_since column
df['new_host'] = df['host_since'].str.split('-').str[0].astype(int)

# Replace years less than 2024 with 0 and years greater than or equal to 2024 with 1
df['new_host'] = df['new_host'].apply(lambda x: 0 if x < 2024 else 1)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21114 entries, 0 to 21114
Data columns (total 45 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              21114 non-null  int64
 1   source                          21114 non-null  object
 2   description                     20560 non-null  object
 3   neighborhood_overview           11111 non-null  object
 4   host_id                         21114 non-null  int64
 5   host_since                      21114 non-null  object
 6   host_location                   15647 non-null  object
 7   host_about                      9846 non-null   object
 8   host_response_time              15043 non-null  object
 9   host_response_rate              15043 non-null  object
 10  host_acceptance_rate            15765 non-null  object
 11  host_is_superhost               20740 non-null  object
 12  host_neighbourhood              8464 non-null   object
 13  host_verifications              21113 non-null  object
 14  host_has_profile_pic            21113 non-null  object
 15  host_identity_verified          21113 non-null  object
 16  neighbourhood                   11112 non-null  object
 17  neighbourhood_cleansed          21114 non-null  object
 18  property_type                   21114 non-null  object
 19  room_type                       21114 non-null  object
 20  accommodates                    21114 non-null  int64
 21  bathrooms                       15901 non-null  float64
 22  bathrooms_text                  21106 non-null  object
 23  bedrooms                        19627 non-null  float64
 24  beds                            15888 non-null  float64
 25  amenities                       21114 non-null  object
 26  price                           15903 non-null  object
 27  minimum_nights                  21114 non-null  int64
 28  maximum_nights                  21114 non-null  int64
 29  minimum_nights_avg_ntm          21114 non-null  float64
 30  maximum_nights_avg_ntm          21114 non-null  float64
 31  has_availability                20090 non-null  object
 32  availability_365                21114 non-null  int64
 33  calendar_last_scraped           21114 non-null  object
 34  number_of_reviews               21114 non-null  int64
 35  number_of_reviews_ltm           21114 non-null  int64
 36  number_of_reviews_l30d          21114 non-null  int64
 37  first_review                    15677 non-null  object
 38  last_review                     15677 non-null  object
 39  review_scores_rating            15677 non-null  float64
 40  license                         10103 non-null  object
 41  instant_bookable                21114 non-null  object
 42  calculated_host_listings_count  21114 non-null  int64
 43  reviews_per_month               15677 non-null  float64
 44  new_host                        21114 non-null  int64
dtypes: float64(7), int64(11), object(27)
memory usage: 7.4+ MB

In [65]:
df_1=df.drop(['host_since'], axis=1)

In [66]:
df_1[['host_response_time', 'host_response_rate', 'host_acceptance_rate']].isnull().sum()

host_response_time      6071
host_response_rate      6071
host_acceptance_rate    5349
dtype: int64

In [67]:
pd.set_option('display.max_rows', None)
index = df_1[['host_response_time', 'host_response_rate', 'host_acceptance_rate']]
for i in index:
    print(df_1[i].value_counts())
    print("-------------------------------")

host_response_time
within an hour        10831
within a few hours     2696
within a day           1066
a few days or more      450
Name: count, dtype: int64
-------------------------------
host_response_rate
100%    12157
90%       385
0%        258
98%       236
80%       223
96%       127
88%       110
92%       106
93%        89
97%        89
94%        89
89%        86
50%        80
86%        75
85%        73
70%        66
67%        63
75%        63
83%        52
73%        43
91%        42
99%        38
84%        38
60%        35
10%        32
95%        32
81%        30
82%        28
33%        28
40%        27
76%        26
77%        23
57%        22
87%        17
4%         17
78%        15
25%        14
20%        13
14%        11
29%        10
79%        10
8%          8
17%         7
30%         6
68%         6
71%         6
22%         4
13%         4
63%         3
72%         3
19%         2
69%         2
38%         2
56%         2
11%         2
39%         1
41%         1
44%         1
54%         1
74%         1
65%         1
26%         1
43%         1
Name: count, dtype: int64
-------------------------------
host_acceptance_rate
100%    5639
98%      695
97%      652
99%      566
0%       526
96%      495
94%      397
88%      366
93%      357
50%      340
92%      334
86%      289
67%      288
95%      282
90%      261
75%      252
89%      250
83%      249
91%      242
80%      192
71%      178
60%      153
87%      146
84%      143
79%      140
81%      125
82%      115
73%      115
33%      112
70%      101
85%      100
77%       93
78%       91
69%       91
64%       83
72%       80
57%       71
68%       68
76%       68
56%       58
63%       54
49%       54
62%       54
59%       50
19%       47
74%       44
40%       41
25%       39
43%       38
46%       37
53%       31
13%       30
58%       25
47%       23
55%       22
38%       22
20%       21
42%       21
17%       21
37%       20
29%       20
65%       18
36%       18
52%       17
31%       16
9%        16
44%       16
61%       15
41%       13
30%       13
66%       12
54%       11
27%       11
48%       11
11%        9
16%        7
15%        7
39%        7
35%        5
26%        5
21%        4
7%         3
22%        3
14%        2
45%        2
18%        2
32%        1
24%        1
6%         1
12%        1
23%        1
Name: count, dtype: int64
-------------------------------

In [68]:
pd.set_option('display.max_rows', None)
index = df_1[['host_response_time', 'host_response_rate', 'host_acceptance_rate']]
for i in index:
    print(df_1[i].value_counts())
    print("-------------------------------")

host_response_time
within an hour        10831
within a few hours     2696
within a day           1066
a few days or more      450
Name: count, dtype: int64
-------------------------------
host_response_rate
100%    12157
90%       385
0%        258
98%       236
80%       223
96%       127
88%       110
92%       106
93%        89
97%        89
94%        89
89%        86
50%        80
86%        75
85%        73
70%        66
67%        63
75%        63
83%        52
73%        43
91%        42
99%        38
84%        38
60%        35
10%        32
95%        32
81%        30
82%        28
33%        28
40%        27
76%        26
77%        23
57%        22
87%        17
4%         17
78%        15
25%        14
20%        13
14%        11
29%        10
79%        10
8%          8
17%         7
30%         6
68%         6
71%         6
22%         4
13%         4
63%         3
72%         3
19%         2
69%         2
38%         2
56%         2
11%         2
39%         1
41%         1
44%         1
54%         1
74%         1
65%         1
26%         1
43%         1
Name: count, dtype: int64
-------------------------------
host_acceptance_rate
100%    5639
98%      695
97%      652
99%      566
0%       526
96%      495
94%      397
88%      366
93%      357
50%      340
92%      334
86%      289
67%      288
95%      282
90%      261
75%      252
89%      250
83%      249
91%      242
80%      192
71%      178
60%      153
87%      146
84%      143
79%      140
81%      125
82%      115
73%      115
33%      112
70%      101
85%      100
77%       93
78%       91
69%       91
64%       83
72%       80
57%       71
68%       68
76%       68
56%       58
63%       54
49%       54
62%       54
59%       50
19%       47
74%       44
40%       41
25%       39
43%       38
46%       37
53%       31
13%       30
58%       25
47%       23
55%       22
38%       22
20%       21
42%       21
17%       21
37%       20
29%       20
65%       18
36%       18
52%       17
31%       16
9%        16
44%       16
61%       15
41%       13
30%       13
66%       12
54%       11
27%       11
48%       11
11%        9
16%        7
15%        7
39%        7
35%        5
26%        5
21%        4
7%         3
22%        3
14%        2
45%        2
18%        2
32%        1
24%        1
6%         1
12%        1
23%        1
Name: count, dtype: int64
-------------------------------

In [69]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21114 entries, 0 to 21114
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              21114 non-null  int64
 1   source                          21114 non-null  object
 2   description                     20560 non-null  object
 3   neighborhood_overview           11111 non-null  object
 4   host_id                         21114 non-null  int64
 5   host_location                   15647 non-null  object
 6   host_about                      9846 non-null   object
 7   host_response_time              15043 non-null  object
 8   host_response_rate              15043 non-null  object
 9   host_acceptance_rate            15765 non-null  object
 10  host_is_superhost               20740 non-null  object
 11  host_neighbourhood              8464 non-null   object
 12  host_verifications              21113 non-null  object
 13  host_has_profile_pic            21113 non-null  object
 14  host_identity_verified          21113 non-null  object
 15  neighbourhood                   11112 non-null  object
 16  neighbourhood_cleansed          21114 non-null  object
 17  property_type                   21114 non-null  object
 18  room_type                       21114 non-null  object
 19  accommodates                    21114 non-null  int64
 20  bathrooms                       15901 non-null  float64
 21  bathrooms_text                  21106 non-null  object
 22  bedrooms                        19627 non-null  float64
 23  beds                            15888 non-null  float64
 24  amenities                       21114 non-null  object
 25  price                           15903 non-null  object
 26  minimum_nights                  21114 non-null  int64
 27  maximum_nights                  21114 non-null  int64
 28  minimum_nights_avg_ntm          21114 non-null  float64
 29  maximum_nights_avg_ntm          21114 non-null  float64
 30  has_availability                20090 non-null  object
 31  availability_365                21114 non-null  int64
 32  calendar_last_scraped           21114 non-null  object
 33  number_of_reviews               21114 non-null  int64
 34  number_of_reviews_ltm           21114 non-null  int64
 35  number_of_reviews_l30d          21114 non-null  int64
 36  first_review                    15677 non-null  object
 37  last_review                     15677 non-null  object
 38  review_scores_rating            15677 non-null  float64
 39  license                         10103 non-null  object
 40  instant_bookable                21114 non-null  object
 41  calculated_host_listings_count  21114 non-null  int64
 42  reviews_per_month               15677 non-null  float64
 43  new_host                        21114 non-null  int64
dtypes: float64(7), int64(11), object(26)
memory usage: 7.2+ MB

In [71]:
# Specify the desired location to save the CSV file
desired_location = "D:\Big Data Analytics- Sem 3\Capstone Project\Toronto\Milestone1&2\listing_clean_1.csv"

# Save the DataFrame as a CSV file
df_1.to_csv(desired_location, index=False)